### PR TITLE
Docker/nginx/php fixes

### PR DESCRIPTION
**Pull request by sigismund**
Fixes related to docker

### CODE REVIEW

**Comment by sigismund** [comment]
The site config wasn't loaded, because of wrong file extension. 
There was also a problem with root folder. It was good idea, trying to separate web and bot code, but the problem is that few files are used by both. 

Other changes I made:
* removed unnecessary `RUN` commands, because every RUN command creates new image.
* uncommented permissions script in DB's dockerfile, because docker automatically adds user with appropriate permissions, when it's creating DB.

**Comment by cryptoeax** [comment]
Thanks a lot for the fixes, much appreciated.  You caught quite a few of my mistakes here.  👍 

Any particular reason why you had to remove  `docker/db-data/.gitignore`?  I'd like to add it back if that's OK, so that when someone clones the repo they get a db-data directory initially (that's why I added the file there.  And I think we can remove the respective entry in `.gitignore`?

**Comment by cryptoeax** [comment]
Also the PHP container doesn't seem to be able to see the db container, I get errors like this:

```
<br />
<b>Warning</b>:  mysqli_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in <b>/var/www/html/lib/mysql.php</b> on line <b>66</b><br />
<br />
<b>Warning</b>:  mysqli_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in <b>/var/www/html/lib/mysql.php</b> on line <b>66</b><br />
<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to mysql_error() must be an instance of mysqli, boolean given, called in /var/www/html/web/WebDB.php on line 34 and defined in /var/www/html/lib/mysql.php:227
Stack trace:
#0 /var/www/html/web/WebDB.php(34): mysql_error(false)
#1 /var/www/html/web/WebDB.php(398): WebDB::connect()
#2 /var/www/html/web/ajax.php(30): WebDB::getStats()
#3 {main}
  thrown in <b>/var/www/html/lib/mysql.php</b> on line <b>227</b><br />
```

**Comment by cryptoeax** [comment]
About benchmarking, I have done it a long time ago, but against PHP5.  It is worth doing again...

**Comment by cryptoeax** [comment]
OK I fixed the PHP container issue, everything is working great now.  Thanks a lot for your help!

**Pull request merged**
